alias addAudioInput='pacmd load-module module-loopback latency_msec=5'
alias addAudioOutput='pacmd load-module module-null-sink sink_name=MySink; pacmd update-sink-proplist MySink device.description=MySink'
alias activate='. venv/bin/activate'
alias cdtmp='cd `mktemp -d`'
alias bat='bat --theme=base-16'
alias emacs='emacsclient -t'
alias emax='emacsclient -c -a emacs'
alias fnmap='sudo nmap -T4 -A'
alias genFilm='ffmpeg -framerate 13 -pattern_type glob -i '\''*.png'\'' -c:v libx264   -r 30 -pix_fmt yuv420p out.mp4'
alias gifGen='ffmpeg -i input.mp4 -vf "split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 output.gif'
alias grep='grep --color=auto'
alias ipy3='ipython3'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias lt='ls -rt'
alias pacman='pacman --color auto'
alias py3='python3'
alias qnmap='sudo nmap -T4 -F'
alias remAudioInput='pacmd unload-module module-loopback'
alias remAudioOutput='pacmd unload-module module-null-sink'
alias torNewCircuit='tor-prompt --run "SIGNAL NEWNYM"'
alias xclip='xclip -selection clipboard'
